# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd v4l2loopback" ];
  boot.extraModulePackages = [config.boot.kernelPackages.v4l2loopback];
  boot.kernelParams = ["quit"
                       "splash"
                       "psmouse.synaptics_intertouch=0"
                       "nvidia-drm.modeset=1"];




  modules.hardware = {
    nvidia.enable = true;
    audio.enable = true;
    wacom.enable = true;
    sensors.enable = true;
    bluetooth.enable = true;
    razer.enable = true;
    };


  fileSystems."/" =
    { device = "/dev/disk/by-uuid/d0a53e3a-bdb4-43ca-bf06-4cb5cc90646b";
      fsType = "ext4";
    };

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/BD1E-1C7E";
      fsType = "vfat";
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/1dc1f689-7b4f-47b4-aa16-3922ff722258"; }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  #networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
	
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
